"""
Chord chart source: 5 verified seed songs + generate-on-the-fly fallback.

Seed songs are hand-verified so the demo is grounded in truth. Anything the
caller names that isn't seeded gets generated by the LLM with a `confident`
flag, so the agent can stay honest about chords it isn't sure of.
"""

import os
import re
import json

# ---------------------------------------------------------------------------
# SEED SONGS — verify each of these yourself before the event. You play guitar,
# so confirm the chords are actually right. These are your demo-safe picks.
# `confident: True` means "we vouch for this."
# ---------------------------------------------------------------------------
SEED_SONGS = {
    "wonderwall": {
        "title": "Wonderwall",
        "artist": "Oasis",
        "verse": ["Em7", "G", "Dsus4", "A7sus4"],
        "chorus": ["C", "Em7", "G", "D"],
        "hard_spots": ["Em7 to G change"],
        "confident": True,
    },
    "let it be": {
        "title": "Let It Be",
        "artist": "The Beatles",
        "verse": ["C", "G", "Am", "F"],
        "chorus": ["C", "G", "F", "C"],
        "hard_spots": ["F chord (barre)"],
        "confident": True,
    },
    "knockin on heavens door": {
        "title": "Knockin' on Heaven's Door",
        "artist": "Bob Dylan",
        "verse": ["G", "D", "Am"],
        "chorus": ["G", "D", "C"],
        "hard_spots": ["keeping steady strum through the change"],
        "confident": True,
    },
    "horse with no name": {
        "title": "A Horse with No Name",
        "artist": "America",
        "verse": ["Em", "D6/9"],
        "chorus": ["Em", "D6/9"],
        "hard_spots": ["the two-finger D6/9 shape"],
        "confident": True,
    },
    "three little birds": {
        "title": "Three Little Birds",
        "artist": "Bob Marley",
        "verse": ["A", "D", "E"],
        "chorus": ["A", "D", "A", "E"],
        "hard_spots": ["clean A to D switch"],
        "confident": True,
    },
}


def _normalize(name: str) -> str:
    """Lowercase, strip punctuation and filler so 'Wonderwall!' matches 'wonderwall'."""
    n = name.lower().strip()
    n = re.sub(r"[^\w\s]", "", n)          # drop punctuation/apostrophes
    n = re.sub(r"\s+", " ", n)             # collapse whitespace
    for filler in ("the song ", "play ", "i want to play ", "can we do "):
        if n.startswith(filler):
            n = n[len(filler):]
    return n.strip()


def _lookup_seed(name: str):
    key = _normalize(name)
    if key in SEED_SONGS:
        return SEED_SONGS[key]
    # loose contains-match so "let it be by the beatles" still hits
    for seed_key, data in SEED_SONGS.items():
        if seed_key in key or key in seed_key:
            return data
    return None


def _llm_client():
    """
    One OpenAI-compatible client. Point it at either OpenAI or the a1mobile
    gateway by setting these env vars — the code is identical either way.

      OpenAI:    OPENAI_API_KEY=sk-...        (no base_url needed)
      a1mobile:  OPENAI_API_KEY=a1hk_...      OPENAI_BASE_URL=https://hack.a1mobile.com/gw/v1
    """
    from openai import OpenAI
    kwargs = {"api_key": os.environ["OPENAI_API_KEY"]}
    base = os.environ.get("OPENAI_BASE_URL")
    if base:
        kwargs["base_url"] = base
    return OpenAI(**kwargs)


def _generate_chart(name: str):
    """Ask the LLM for a chart in our exact JSON shape. Never trust it blindly —
    it returns confident=false when it isn't sure, and the agent says so."""
    model = os.environ.get("LLM_MODEL", "gpt-4o-mini")
    client = _llm_client()
    resp = client.chat.completions.create(
        model=model,
        messages=[
            {
                "role": "system",
                "content": (
                    "You are a guitar chord reference. Return ONLY valid JSON, "
                    "no markdown fences, no prose. Use this exact shape: "
                    '{"title": str, "artist": str, "verse": [str], '
                    '"chorus": [str], "hard_spots": [str], "confident": bool}. '
                    "Give real, playable open or common chord names (e.g. G, Em7, Cadd9). "
                    "Set confident=false if you are not certain these are the exact "
                    "chords for this specific song. Do not invent a song that "
                    "doesn't exist — if unknown, set confident=false and give a "
                    "plausible common progression."
                ),
            },
            {"role": "user", "content": f"Chords for the song: {name}"},
        ],
    )
    raw = resp.choices[0].message.content.strip()
    raw = raw.replace("```json", "").replace("```", "").strip()
    data = json.loads(raw)
    # guarantee the fields our coaching code reads, even if the model skimps
    data.setdefault("title", name.title())
    data.setdefault("artist", "")
    data.setdefault("verse", [])
    data.setdefault("chorus", [])
    data.setdefault("hard_spots", [])
    data.setdefault("confident", False)
    data["source"] = "generated"
    return data


def get_chart(name: str):
    """
    The one function the server calls. Returns (chart_dict, source) where
    source is 'seed' or 'generated'. On any LLM failure returns (None, 'error')
    so the agent can say honestly that it couldn't find the song.
    """
    seed = _lookup_seed(name)
    if seed:
        chart = dict(seed)
        chart["source"] = "seed"
        return chart, "seed"
    try:
        return _generate_chart(name), "generated"
    except Exception as e:
        print(f"[songs] generate failed for {name!r}: {e}")
        return None, "error"


if __name__ == "__main__":
    # quick local sanity check without telephony
    for probe in ["Wonderwall", "let it be", "Free Fallin"]:
        chart, src = get_chart(probe)
        print(f"{probe!r:20} -> source={src}  {chart}")
